service: sample-app
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: GET
          cors: true
      - http: 
          path: /users
          method: GET
          cors: true
      - http: 
          path: /users/post
          method: POST
          cors: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors: true